#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/projlocator
  
  rm -rf build/* tmp/* 
  
  pySloc -L py pl_projects pl_projRelPath  -X cover -X htmlcov -X dist -v $@
else
  echo "DEV_BASE is not defined"
fi
