#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/projlocator
  
  rm -rf build/* tmp/* 
  
  pySloc -L py  -X cover -X htmlcov -X dist -v $@ src/projlocator src/pl_projects src/pl_projRelPath tox.ini requirements.txt test_requirements.txt tests/test_dir_lang_maps.py tests/test_lang_for_projects.py tests/test_proj_dir_from_name.py tests/test_proj_list.py tests/test_rel_path_for_projects.py setup.py
else
  echo "DEV_BASE is not defined"
fi
