[meta]
version = "0.1.0"

[project]
name = "projlocator"
package = "projlocator"
main_lang = "py"
version = "0.0.11"
version_date = "2018-03-22"
author = "Jim Dixon"
author_email = "jddixon@gmail.com"
copyright = "2016-2017"
description = "manage software projects organized by language"
dev_status = "alpha"
relpath = "py/projlocator"
license = "mit"
state = "shared"
url = "https://jddixon.github.io/projlocator"

[py]
packages = [ "projlocator",]
package_dir = [ "src",]
test_dir = [ "tests",]
py_modules = []
scripts = [ "src/pl_projects", "src/pl_projRelPath",]
ext_modules = []
distshare = [ "optionz", "rnglib",]
env_vars = [ "DEV_BASE", "HOME",]
requirements = [ "setuptools",]
test_requirements = []
